version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - target/my-web-app.war
    - .ebextensions/**/*